// Code generated by goctl. DO NOT EDIT.
package types

type IndexContentResp struct {
	HotMessage     []string          `json:"hotMessage"`
	MessageInfo    map[string]string `json:"messageInfo"`
	ProductPicture []string          `json:"productPicture"`
}
