// Code generated by goctl. DO NOT EDIT.
package types

type GetCodeReq struct {
	Email string `json:"email"`
}

type GetCodeResp struct {
	Code string `json:"code"`
}

type RegisterReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Mobile   string `json:"mobile"`
	Email    string `json:"email"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type ResetPwdReq struct {
	Mobile     string `json:"mobile"`
	AssessCode string `json:"assessCode"`
	Password   string `json:"password"`
}

type ResetPwdResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type UserInfoResp struct {
	UserName string `json:"userName"`
	Mobile   string `json:"mobile"`
	Email    string `json:"email"`
}
