// Code generated by goctl. DO NOT EDIT.
// Source: usercenter.proto

package server

import (
	"context"

	"MyRainFarm/application/user/rpc/internal/logic"
	"MyRainFarm/application/user/rpc/internal/svc"
	"MyRainFarm/application/user/rpc/pb"
)

type UserCenterServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedUserCenterServer
}

func NewUserCenterServer(svcCtx *svc.ServiceContext) *UserCenterServer {
	return &UserCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCenterServer) Register(ctx context.Context, in *__.RegisterRequest) (*__.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserCenterServer) Login(ctx context.Context, in *__.LoginRequest) (*__.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserCenterServer) RePwd(ctx context.Context, in *__.RePwdRequest) (*__.RePwdResponse, error) {
	l := logic.NewRePwdLogic(ctx, s.svcCtx)
	return l.RePwd(in)
}

func (s *UserCenterServer) Detail(ctx context.Context, in *__.UserInfoRequest) (*__.UserInfoResponse, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}

func (s *UserCenterServer) GetCode(ctx context.Context, in *__.UserCodeRequest) (*__.UserCodeResponse, error) {
	l := logic.NewGetCodeLogic(ctx, s.svcCtx)
	return l.GetCode(in)
}
