CREATE TABLE `user` (
	`snow` bigint NOT NULL COMMENT '用户雪花签名',
	`name` VARCHAR ( 30 ) NOT NULL UNIQUE DEFAULT '' COMMENT '用户名',
	`password` VARCHAR ( 255 ) NOT NULL DEFAULT '' COMMENT '用户密码',
	`mobile` VARCHAR ( 13 ) NOT NULL UNIQUE DEFAULT '' COMMENT '用户电话',
	`email` VARCHAR ( 30 ) NOT NULL UNIQUE DEFAULT '' COMMENT '用户邮箱',
	`create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY ( `name` )
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;