// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	indexContent "MyRainFarm/application/indexContent/api/internal/handler/indexContent"
	"MyRainFarm/application/indexContent/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/indexContent",
				Handler: indexContent.IndexContentHandler(serverCtx),
			},
		},
		rest.WithPrefix("/indexContent/v1"),
	)
}
